<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Confidence Intervals Practice


---

In [1]:
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

### Q 1:

Height measurements of 200 individuals resulted in an observed mean of 174 cm. General estimates indicate a standard deviation of 6 cm for heights. What are the 95 % confidence intervals for the measured mean? 

In [2]:
stats.norm().ppf([0.025,0.975])

array([-1.95996398,  1.95996398])

In [3]:
174+stats.norm().ppf([0.025,0.975])*6/np.sqrt(200)

array([173.16845771, 174.83154229])

### Q 2:

In a psychological experiment, the reaction time of people playing computer games is estimated to have a variance of 0.05 seconds. How many samples does one have to collect to be 95 % (99 %) sure that the error in the estimate of the mean reaction time is not larger than 0.01 seconds?

In [4]:
sigma = 0.05**0.5
max_error = 0.01
n = (stats.norm().ppf([0.975,0.995])*sigma/max_error)**2
print(n)

[1920.72941035 3317.44830051]


In [5]:
(stats.norm().ppf(0.975)*sigma/max_error)**2

1920.7294103470626

### Q 3:

You have a huge box with tennis balls of which you are not sure if they conform with rules for size (must be between 6.54 and 6.86 cm in diameter). You pick 10 of the balls and measure their diameter, obtaining a mean of 6.58 cm and a sample standard deviation of 0.04 cm. Find 95 % and 99 % confidence intervals. Can you be confident that the balls in the box conform with the rules?

In [6]:
def t_int(mean,std,n,lower,upper):
    return mean+stats.t(n-1).ppf([lower,upper])*std/np.sqrt(n)

In [7]:
t_int(6.58,0.04,10,0.025,0.975)

array([6.55138572, 6.60861428])

In [8]:
t_int(6.58,0.04,10,0.005,0.995)

array([6.53889247, 6.62110753])