<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Linear algebra practice

---

In [1]:
import numpy as np

#### 1. Transform the following two vectors into numpy arrays.

In [2]:
vec_1 = [2, 4, 1]
vec_2 = [1, 3, 0]

In [3]:
vec_1 = np.array(vec_1)
vec_2 = np.array(vec_2)

#### 2. For the two vectors, calculate
    
- $3 \cdot {\rm vec}_1 + 2\cdot {\rm vec}_2$
- $-0.5\cdot {\rm vec}_1 + 3\cdot {\rm vec}_2$ 
- the scalar product 
- the magnitude of each vector

In [4]:
print(3*vec_1+2*vec_2)
print(-0.5*vec_1+3*vec_2)
print(vec_1.dot(vec_2))
print(np.linalg.norm(vec_1))
print(np.linalg.norm(vec_2))

[ 8 18  3]
[ 2.   7.  -0.5]
14
4.58257569495584
3.1622776601683795


#### 3. Transform the following lists into numpy matrices.

In [5]:
A = [[2,1],[-2,3]]
B = [[1,3,4],[0,1,2],[1,0,0]]
C = [[2,3,0],[0,1,4],[1,0,1]]

In [6]:
A = np.array(A)
B = np.array(B)
C = np.array(C)

#### 4. Extract the row and column vectors from A.

In [7]:
A[0,:], A[1,:]

(array([2, 1]), array([-2,  3]))

In [8]:
A[:,0], A[:,1]

(array([ 2, -2]), array([1, 3]))

In [9]:
len(A)

2

In [10]:
list(range(A.shape[1]))

[0, 1]

In [11]:
print(A)

[[ 2  1]
 [-2  3]]


In [12]:
[A[:,i] for i in range(A.shape[1])]

[array([ 2, -2]), array([1, 3])]

In [13]:
list(A.T)

[array([ 2, -2]), array([1, 3])]

#### 5. Form the matrix products $B\cdot C$ and $C\cdot B$. Compare!

In [14]:
print(B.dot(C)) 
print(C.dot(B))

[[ 6  6 16]
 [ 2  1  6]
 [ 2  3  0]]
[[ 2  9 14]
 [ 4  1  2]
 [ 2  3  4]]


#### 6. Form the dot products $B\cdot {\rm vec}_1$ and ${\rm vec}_1\cdot B$. Compare!

In [15]:
print(B.dot(vec_1))
print(vec_1.dot(B))

[18  6  2]
[ 3 10 16]


#### 7. Obtain the transpose of the matrices $A$, $B$, $C$.

In [16]:
print(A.T)
print(B.T)
print(C.T)

[[ 2 -2]
 [ 1  3]]
[[1 0 1]
 [3 1 0]
 [4 2 0]]
[[2 0 1]
 [3 1 0]
 [0 4 1]]


#### 8. Form the matrix product $A^T \cdot A$ and $A\cdot A^T$. Compare! Repeat for the matrices $B$ and $C$. Do you notice anything special about the resulting matrices?

In [17]:
print(A.T.dot(A))
print(A.dot(A.T))
print(B.T.dot(B))
print(B.dot(B.T))
print(C.T.dot(C))
print(C.dot(C.T))

[[ 8 -4]
 [-4 10]]
[[ 5 -1]
 [-1 13]]
[[ 2  3  4]
 [ 3 10 14]
 [ 4 14 20]]
[[26 11  1]
 [11  5  0]
 [ 1  0  1]]
[[ 5  6  1]
 [ 6 10  4]
 [ 1  4 17]]
[[13  3  2]
 [ 3 17  4]
 [ 2  4  2]]


#### 9. Calculate the inverse matrices of $A$, $B$ and $C$ if possible. Check that the found matrices are indeed the inverses by taking the matrix product with the original matrices.

In [18]:
print(np.linalg.inv(A))
print(np.linalg.inv(B))
print(np.linalg.inv(C))

[[ 0.375 -0.125]
 [ 0.25   0.25 ]]
[[ 0.00000000e+00  2.22044605e-16  1.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00 -1.00000000e+00]
 [-5.00000000e-01  1.50000000e+00  5.00000000e-01]]
[[ 0.07142857 -0.21428571  0.85714286]
 [ 0.28571429  0.14285714 -0.57142857]
 [-0.07142857  0.21428571  0.14285714]]


In [19]:
print(np.linalg.inv(A).dot(A))
print(np.linalg.inv(B).dot(B))
print(np.linalg.inv(C).dot(C))

[[1. 0.]
 [0. 1.]]
[[1.00000000e+00 2.22044605e-16 4.44089210e-16]
 [0.00000000e+00 1.00000000e+00 4.44089210e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
[[ 1.00000000e+00 -1.66533454e-16  1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [20]:
print(np.allclose(np.linalg.inv(A).dot(A),np.eye(len(A))))
print(np.allclose(np.linalg.inv(B).dot(B),np.eye(len(B))))
print(np.allclose(np.linalg.inv(C).dot(C),np.eye(len(C))))

True
True
True


#### 10. Solve the system of equations

$$
\begin{eqnarray}
2\, x_1 + 1\, x_2 &=& 3\\
-2\, x_1 + 3\, x_2 &=& 1
\end{eqnarray}$$

Note that this system of equations can be written as

$$
\left(
\begin{array}{cc}
2&1\\
-2&3
\end{array}
\right)
\left(
\begin{array}{c}
x_1\\
x_2 
\end{array}
\right)
=
\left(
\begin{array}{c}
3\\
1 
\end{array}
\right)
$$

Find out how to use the command `np.linalg.solve` to solve this system of equations.

In [21]:
b = np.array([3,1])
np.linalg.solve(A,b)

array([1., 1.])

#### 11. Check that the same result can be obtained by calculating

$$
\left(
\begin{array}{cc}
2&1\\
-2&3
\end{array}
\right)^{-1}
\left(
\begin{array}{c}
3\\
1 
\end{array}
\right)
$$

In [22]:
np.linalg.inv(A).dot(b)

array([1., 1.])

### In the following exercises, work purely with python lists to create your own functions which do the same as the numpy functions. Verify your results with the examples from above.

In [23]:
vec_1 = [2, 4, 1]
vec_2 = [1, 3, 0]
A = [[2,1],[-2,3]]
B = [[1,3,4],[0,1,2],[1,0,0]]
C = [[2,3,0],[0,1,4],[1,0,1]]

#### 12. Write a function that adds two vectors to each other

In [24]:
def vec_add(vec_1,vec_2):
    vec_sum = [sum(comp) for comp in zip(vec_1,vec_2)]
    return vec_sum

In [25]:
vec_add(vec_1,vec_2)

[3, 7, 1]

#### 13. Write a function that subtracts two vectors from each other

In [26]:
def vec_sub(vec_1,vec_2):
    vec_sub = [(comp[0]-comp[1]) for comp in zip(vec_1,vec_2)]
    return vec_sub

In [27]:
vec_sub(vec_1,vec_2)

[1, 1, 1]

#### 14. Write a function that multiplies a vector by a number

In [28]:
def vec_mult(vec,mult=1):
    return [mult*v for v in vec]

In [29]:
vec_mult(vec_1,3)

[6, 12, 3]

#### 15. Write a function that calculates the length of a vector

In [30]:
def vec_len(vec):
    vec_len = sum(comp**2 for comp in vec)**0.5
    return vec_len

In [31]:
vec_len(vec_2)

3.1622776601683795

#### 16. Write a function that calculates the scalar product of two vectors

In [32]:
def vec_dot(vec_1,vec_2):
    vec_dot = sum((comp[0]*comp[1]) for comp in zip(vec_1,vec_2))
    return vec_dot

In [33]:
vec_dot(vec_1,vec_2)

14

#### 17. Write a function that returns the rows of a matrix

In [34]:
def matrix_rows(A):
    rows = []
    for k in range(len(A)):
         rows.append([A[k][i] for i in range(len(A[0]))])
    return rows

In [35]:
matrix_rows(B)

[[1, 3, 4], [0, 1, 2], [1, 0, 0]]

#### 18. Write a function that returns the columns of a matrix

In [36]:
def matrix_columns(A):
    columns = []
    for k in range(len(A[0])):
         columns.append([A[i][k] for i in range(len(A))])
    return columns

In [37]:
matrix_columns(B)

[[1, 0, 1], [3, 1, 0], [4, 2, 0]]

#### 19. Write a function that multiplies a matrix with a vector

In [38]:
def mat_vec_dot(A,vec):
    vec_temp = [vec_dot(row,vec) for row in matrix_rows(A)]
    return vec_temp

In [39]:
mat_vec_dot(B,vec_1)

[18, 6, 2]

#### 20. Write a function that multiplies a matrix with a matrix 

In [40]:
def mat_mat_dot(A,B):
    prod = [[vec_dot(row,column) for column in matrix_columns(B)] for row in matrix_rows(A)]
    return prod

In [41]:
mat_mat_dot(B,C)

[[6, 6, 16], [2, 1, 6], [2, 3, 0]]

#### 21. Write a function that returns the transpose of a given matrix

In [42]:
def mat_transpose(A):
    C = []
    for i in range(len(A)):
        vec_temp = []
        for j in range(len(A)):
            vec_temp.append(A[j][i])
        C.append(vec_temp)
    return C

In [43]:
mat_transpose(B)

[[1, 0, 1], [3, 1, 0], [4, 2, 0]]